{% set name = "torch-simplify" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torch-simplify-{{ version }}.tar.gz
  sha256: 945a2448b79dd90f8d9d671028a235fa73be71e573f993e9bfe454ddf307a7cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch
    - torchvision

test:
  imports:
    - simplify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/EIDOSlab/simplify
  summary: Simplification of pruned models for accelerated inference
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TJHeeringa
